services:
  db:
    container_name: "postgresql"
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=appdb
      - POSTGRES_USER=myUserName
      - POSTGRES_PASSWORD=myPassword